
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost/movieapp
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=bus-refresh

#RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
